version: '3.3'
services:
  rest-service:
    container_name: rest_service
    build:
      dockerfile: Dockerfile
    ports:
      - 8088:8088
    environment:
      - mysql://db-rest-service/saranghaengbok_rest